trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:
  - job: Build_API
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
        packageType: sdk
      displayName: 'Install .NET Core'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        workingDirectory: $(Build.SourcesDirectory)\bookmark-browser-api
      displayName: 'Build the project'
#    - task: DotNetCoreCLI@2
#      inputs:
#        command: test
#        arguments: '--configuration $(buildConfiguration)'
#        projects: '**/*Tests/*.csproj'
#      displayName: 'Run unit tests'
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)\bookmark-browser-api-output'
        workingDirectory: $(Build.SourcesDirectory)\bookmark-browser-api
        zipAfterPublish: false
      displayName: 'Create API deployment artifact'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\bookmark-browser-api-output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)\bookmark-browser-api-$(Build.BuildId).zip'
      displayName: 'Create API artifact'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\bookmark-browser-api-$(Build.BuildId).zip'
        ArtifactName: bookmark-browser-api
      displayName: 'Publish API artifact'
  - job: Build_UI
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Install project dependencies'
    - script: |
        npm run build
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Build the project'
    - script: |
        npm run test
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Run unit tests'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)\bookmark-browser\build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
      displayName: 'Create UI artifact'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
        ArtifactName: bookmark-browser
      displayName: 'Publish UI artifact'
