trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
        restoreDirectory: $(Build.SourcesDirectory)\bookmark-browser-api\packages
      displayName: 'Install API dependencies'
    - task: VSBuild@1
      inputs:
        solution: '$(Build.SourcesDirectory)\bookmark-browser-api\$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
      displayName: 'Build the API'
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Install UI dependencies'
    - script: |
        npm run build
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Build the UI'
    - script: |
        npm run test
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Run UI unit tests'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)\bookmark-browser-api\bin'
        contents: '*.dll'
        targetFolder: '$(Build.SourcesDirectory)\bookmark-browser\build\bin'
      displayName: 'Copy API build output'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)\bookmark-browser-api'
        contents: 'global.asax'
        targetFolder: '$(Build.SourcesDirectory)\bookmark-browser\build'
      displayName: 'Copy global.asax'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)\bookmark-browser-api'
        contents: 'web.config'
        targetFolder: '$(Build.SourcesDirectory)\bookmark-browser\build'
      displayName: 'Copy web.config'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)\bookmark-browser\build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
      displayName: 'Create artifact'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
        ArtifactName: bookmark-browser
      displayName: 'Publish artifact'
