trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Install NuGet'
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser-api
      displayName: 'Retrieve NuGet packages'
    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'
        platform: 'Any CPU'
        configuration: '$(buildConfiguration)'
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser-api
      displayName: 'Build the API'
    #- task: VSTest@2
    #  inputs:
    #    platform: '$(buildPlatform)'
    #    configuration: '$(buildConfiguration)'
    #  displayName: 'Run API unit tests'
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Install UI dependencies'
    - script: |
        npm run build
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Build the UI'
    - script: |
        npm run test
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Run UI unit tests'
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)\bookmark-browser-api\bin\$(buildConfiguration)'
        contents: '**'
        targetFolder: '$(Build.SourcesDirectory)\bookmark-browser\build'
      displayName: 'Combine build output'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)\bookmark-browser\build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
      displayName: 'Create artifact'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
        ArtifactName: bookmark-browser
      displayName: 'Publish artifact'
