trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:
  - job: Build_API
    steps:
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
        packageType: sdk
      displayName: 'Install .NET Core'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        workingDirectory: $(Build.SourcesDirectory)\bookmark-browser-api
      displayName: 'Build the project'
    #- task: DotNetCoreCLI@2
    #  inputs:
    #    command: test
    #    arguments: '--configuration $(buildConfiguration)'
    #    projects: '**/*Tests/*.csproj'
    #  displayName: 'Run unit tests'
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)\bookmark-browser-deploy'
        workingDirectory: $(Build.SourcesDirectory)\bookmark-browser-api
        zipAfterPublish: false
      displayName: 'Publish API build'
  - job: Build_UI
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Install project dependencies'
    - script: |
        npm run build
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Build the project'
    - script: |
        npm run test
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Run unit tests'
  - job: Publish_Artifact
    dependsOn:
    - Build_API
    - Build_UI
    steps:
      - task: CopyFiles@2
          - sourceFolder: '$(Build.SourcesDirectory)\bookmark-browser\build'
          - contents: '**'
          - targetFolder: '$(Build.ArtifactStagingDirectory)\bookmark-browser-deploy'
        displayName: 'Combine build output'
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\bookmark-browser-deploy'
            includeRootFolder: false
            archiveType: zip
            archiveFile: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
          displayName: 'Create deployment artifact'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
          ArtifactName: bookmark-browser
        displayName: 'Publish artifact'
