trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
      workingDirectory: $(Build.SourcesDirectory)/bookmark-browser/bookmark-browser-api
      displayName: 'Install API dependencies'

    - script: |
        npm install
      workingDirectory: $(Build.SourcesDirectory)/bookmark-browser
      displayName: 'Install UI dependencies'
    - script: |
        npm run build
      workingDirectory: $(Build.SourcesDirectory)/bookmark-browser
      displayName: 'Build the UI'
    - script: |
        npm run test
      workingDirectory: $(Build.SourcesDirectory)\bookmark-browser
      displayName: 'Run UI unit tests'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)/bookmark-browser-api'
        contents: '*.*'
        targetFolder: '$(Build.SourcesDirectory)\bookmark-browser\build\api'
      displayName: 'Copy API source'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)\bookmark-browser\build'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
      displayName: 'Create artifact'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\bookmark-browser-$(Build.BuildId).zip'
        ArtifactName: bookmark-browser
      displayName: 'Publish artifact'
