trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'Install project dependencies'
    - script: |
        npm run build
      displayName: 'Build the project'
    - script: |
        npm run test
      displayName: 'Run unit tests'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: build
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)-$(Build.BuildId).zip'
      displayName: 'Create deployment artifact'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)-$(Build.BuildId).zip'
        ArtifactName: bookmark-browser
      displayName: 'Publish artifact'
